Спринт 13 Первый коммит
fen1x63/java-shareit pull request #1
Opened 2023-09-18 09:59 UTC by fen1x63

2023-09-18 10:04 UTC, fen1x63 commented
Изменена приватность репозитория

2023-09-18 19:28 UTC, NikolaiDem requested changes

2023-09-18 19:28 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/user/model/UserDto.java
> +public class UserDto {
А Update аннотация для каких полей должна использоваться?

2023-09-29 11:18 UTC, NikolaiDem approved these changes

2023-10-06 13:04 UTC, merged