Спринт 15 Первый коммит
fen1x63/java-shareit pull request #1
Opened 2023-12-12 10:05 UTC by fen1x63

2023-12-13 09:22 UTC, NikolaiDem requested changes

2023-12-13 09:22 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemController.java
>  /**
Еще нужен @Validated для аннотаций валидации

2023-12-13 09:22 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
>  public class BookingController {
Добавить логирование эндпоинтов, аналогично для остальных контроллеров

2023-12-13 09:22 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/repository/MemoryItem.java
> +//    List<Item> findByOwnerId(int userId);
Удалить закомментированный код

2023-12-13 09:22 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                    List<CommentDto> comments = memoryComment.findByItemIdOrderByCreatedDesc(item.getId()).stream()
memory.findByItemIdOrderByCreatedDesc(...) создает проблему N+1 запроса. Нужно выгрузить комментарии для всех предметов

2023-12-13 09:22 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            booking = bookings.get(0);
Почему last бронирование по индексу 0?

2023-12-13 09:22 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            booking = bookings.get(1);
Почему last бронирование по индексу 1?

2023-12-13 09:22 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/service/RequestServiceImpl.java
> +//        List<Item> items = memoryItem.findAllByRequestRequestorId(userId);
Вернуть закомментированный код

2023-12-13 09:22 UTC, NikolaiDem commented on src/test/java/ru/practicum/shareit/repository/ItemStorageTest.java
> +public class ItemStorageTest {
Нужен еще тест для MemoryItem

2023-12-13 09:22 UTC, NikolaiDem commented on src/test/java/ru/practicum/shareit/repository/ItemStorageTest.java
> +        );
В тесте должно что-то проверяться

2023-12-13 09:22 UTC, NikolaiDem commented on src/test/java/ru/practicum/shareit/unit/ItemRequestServiceTest.java
> +public class ItemRequestServiceTest {
Еще нужны интеграционные тесты для каждой фичи

2023-12-17 11:09 UTC, fen1x63 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            booking = bookings.get(0);
Проверка что список не пустой

2023-12-17 11:09 UTC, fen1x63 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            booking = bookings.get(1);
Проверка что в списке как минимум 2 элемента

2023-12-17 18:32 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            booking = bookings.get(0);
Что гарантирует, что last бронирование всегда будет по индексу 1?

2023-12-17 18:33 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            booking = bookings.get(1);
Что гарантирует, что next бронирование будет по индексу 1?

2023-12-19 07:40 UTC, Ivanov-s-tmn commented on pom.xml
> +                                                <maximum>6</maximum>
Эти значения изменять не нужно, они установлены для плагина и проверяют покрытие тестами

2023-12-19 07:40 UTC, Ivanov-s-tmn commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        return (!(booking == null || booking.getStart() == null || booking.getEnd() == null) && ((booking.getStart().isAfter(bookingDtoDefault.getStart()) && booking.getStart().isBefore(bookingDtoDef
Можно упростить условие проверки на пересечение. Если время старта новой брони позже времени окончания существующих ИЛИ время конца новой брони меньше времени окончания существующих, тогда пересечения нет.
Лучше сделать эту проверку запросом к БД

2023-12-21 11:54 UTC, Ivanov-s-tmn commented on src/test/java/ru/practicum/shareit/unit/ItemServiceIntegrationTest.java
В интеграционных тестах, где проверяется взаимодействие с БД, ее лучше всегда очищать от данных, для этого можно использовать метод `@AfterEach` и так же можно создавать и добавлять какие-то общие данные, которые будут применятся для всех или почти всех тестов, например `memoryUser.save(user);` так же перед каждым в `@BeforeEach` методе

2023-12-21 17:01 UTC, merged