Спринт 16 Первый коммит
fen1x63/java-shareit pull request #2
Opened 2023-12-21 20:44 UTC by fen1x63

2023-12-22 11:02 UTC, fen1x63 commented
Не понимаю почему не проходит POSTMAN тест GET {{baseUrl}}/requests

2023-12-23 09:32 UTC, NikolaiDem requested changes

2023-12-23 09:32 UTC, NikolaiDem commented on server/src/main/resources/application.properties
> +spring.datasource.url=${SPRING_DATASOURCE_URL}
А где задается SPRING_DATASOURCE_URL?
С помощью переменных контейнера можно сделать:
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}

2023-12-23 10:17 UTC, fen1x63 commented on server/src/main/resources/application.properties
> +spring.datasource.url=${SPRING_DATASOURCE_URL}
В Docker compose

2023-12-24 13:01 UTC, NikolaiDem approved these changes

2023-12-24 13:39 UTC, merged