Спринт 14 Первый коммит
fen1x63/java-shareit pull request #2
Opened 2023-10-09 12:05 UTC by fen1x63

2023-10-10 10:09 UTC, NikolaiDem requested changes

2023-10-10 10:09 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/handler/ErrorHandler.java
> +        log.info(LogError.INCORRECT_REQUEST.getMessage());
log.error(...)

2023-10-10 10:09 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/handler/ErrorHandler.java
> +    @ExceptionHandler
Исключения с одинаковой обработкой можно собрать в один метод
    @ExceptionHandler({ConstraintViolationException.class, NotFoundException.class})

2023-10-10 10:09 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +    @Query("SELECT i FROM Item i "
Как приоритет у операторов OR и AND?

2023-10-10 10:09 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        if (!bookings.isEmpty() && bookings.get(0).getStart().isBefore(LocalDateTime.now())) {
Почему проверка по 1-му бронированию?

2023-10-10 10:09 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +    public Long findOwnerId(Long itemId) {
Не используется

2023-10-10 11:36 UTC, fen1x63 commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    void save(BookingStatus status, Long bookingId);
Это может быть полезно в случаях, когда вам нужно выполнить быстрое обновление без извлечения и сохранения полных данных сущности Booking.

2023-10-12 20:07 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/dto/InputBookingDto.java
> +@Data
Исправлено не для всех классов

2023-10-12 20:37 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +        switch (state) {
Лучше использовать BookingTimeStatus как в предыдущем методе

2023-10-12 20:37 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/handler/ErrorHandler.java
> +        if (e instanceof ConstraintViolationException) {
Вместо использования instance of сделать отдельный метод. В предыдущем комментарии я предложил объединить их в один метод, если у них абсолютно одинаковая реализация)

2023-10-12 20:37 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> -@Validated
Удалять не нужно, используются аннотации валидации

2023-10-12 20:37 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +    public ShortItemBookingDto searchLastBookingByItemId(List<OutputBookingDto> bookings) {
Код дублируется с updateItems. Сделать рефакторинг
Аналогично для searchNextBookingByItemId

2023-10-12 20:37 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +@ToString
Исправлено не для всех моделей

2023-10-15 09:44 UTC, NikolaiDem approved these changes

2023-10-15 09:44 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +    public void updateItems(ItemDto itemDto) {
public void setNextLastBookings(ItemDto itemDto) {
        List<Booking> bookings = bookingRepository.findBookingsItem(itemDto.getId());
        findLastBooking(bookings)
                .ifPresent(itemDto::setLastBooking);
        findNextBooking(bookings)
                .ifPresent(itemDto::setNextBooking);
    }

    private Optional<ShortItemBookingDto> findNextBooking(List<Booking> bookings) {
        return bookings.stream()
                .filter(obj -> (obj.getStatus().equals(BookingStatus.APPROVED)))
                .filter(obj -> obj.getStart().isAfter(LocalDateTime.now()))
                .min(Comparator.comparing(Booking::getStart))
                .map(BookingMapper::toItemBookingDto);
    }

    private Optional<ShortItemBookingDto> findLastBooking(List<Booking> bookings) {
        return bookings.stream()
                .filter(obj -> (obj.getStatus().equals(BookingStatus.APPROVED)))
                .filter(obj -> obj.getStart().isBefore(LocalDateTime.now()))
                .min((obj1, obj2) -> obj2.getStart().compareTo(obj1.getStart()))
                .map(BookingMapper::toItemBookingDto);
    }

2023-10-15 09:44 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        List<OutputBookingDto> bookings = bookingRepository.findAllByItemIdIn(itemIds).stream()
Map<Long, List<Booking>> bookingsByItemId = bookingRepository.findAllByItemIdIn(itemIds).stream()
                .collect(Collectors.groupingBy(bookingDto -> bookingDto.getItem().getId()));

        items.forEach(itemDto -> {
            itemDto.setComments(commentsByItemId.getOrDefault(itemDto.getId(), new ArrayList<>()));
            findLastBooking(bookingsByItemId.getOrDefault(itemDto.getId(), new ArrayList<>()))
                    .ifPresent(itemDto::setLastBooking);
            findNextBooking(bookingsByItemId.getOrDefault(itemDto.getId(), new ArrayList<>()))
                    .ifPresent(itemDto::setNextBooking);
        });

2023-10-25 10:28 UTC, merged